# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# GoReleaser configuration for go-ddd project
# Documentation: https://goreleaser.com

version: 2

project_name: go-ddd

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: service
    main: ./cmd/service
    binary: service
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.ShortCommit}}
      - -X main.Date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "Features"
      regexp: '^feat(\(.+\))?!?:'
      order: 0
    - title: "Bug Fixes"
      regexp: '^fix(\(.+\))?!?:'
      order: 1
    - title: "Performance"
      regexp: '^perf(\(.+\))?!?:'
      order: 2
    - title: "Refactor"
      regexp: '^refactor(\(.+\))?!?:'
      order: 3
    - title: "Others"
      order: 999

dockers_v2:
  - id: service
    ids:
      - service
    dockerfile: Dockerfile
    images:
      - ghcr.io/blackhorseya/go-ddd
    tags:
      - "{{ .Version }}"
      - "{{ .Major }}.{{ .Minor }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.source: "https://github.com/blackhorseya/go-ddd"
      org.opencontainers.image.description: "Go DDD template project"

release:
  github:
    owner: blackhorseya
    name: go-ddd
  draft: false
  prerelease: auto
  mode: replace
  name_template: "v{{ .Version }}"
