receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

connectors:
  servicegraph:
    latency_histogram_buckets: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5]
    dimensions:
      - service.namespace
    store:
      ttl: 2s
      max_items: 200
  spanmetrics:
    histogram:
      explicit:
        buckets: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10]
    dimensions:
      - name: http.request.method
      - name: http.response.status_code
      - name: http.route

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024

exporters:
  otlphttp/tempo:
    endpoint: "http://tempo:4318"
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/tempo, servicegraph, spanmetrics, debug]
    metrics:
      receivers: [otlp, servicegraph, spanmetrics]
      processors: [batch]
      exporters: [prometheus, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, debug]
