// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	handler2 "github.com/blackhorseya/go-ddd/internal/identity/adapter/http/handler"
	"github.com/blackhorseya/go-ddd/internal/identity/application/usecase"
	"github.com/blackhorseya/go-ddd/internal/identity/infrastructure/auth"
	"github.com/blackhorseya/go-ddd/internal/identity/infrastructure/idgen"
	"github.com/blackhorseya/go-ddd/internal/identity/infrastructure/persistence"
	"github.com/blackhorseya/go-ddd/internal/identity/infrastructure/persistence/postgres"
	"github.com/blackhorseya/go-ddd/internal/shared/adapter/grpc"
	"github.com/blackhorseya/go-ddd/internal/shared/adapter/http"
	"github.com/blackhorseya/go-ddd/internal/shared/adapter/http/handler"
	"github.com/blackhorseya/go-ddd/internal/shared/infrastructure/config"
	"github.com/blackhorseya/go-ddd/internal/shared/infrastructure/messaging/watermill"
)

// Injectors from wire.go:

// InitializeApp builds the application with all dependencies wired up.
// The returned cleanup releases resources held by providers, such as the database pool.
func InitializeApp(cfg *config.AppConfig) (*App, func(), error) {
	server := provideHTTPServer(cfg)
	grpcServer := provideGRPCServer(cfg)
	healthHandler := handler.NewHealthHandler()
	persistenceConfig := providePersistenceConfig(cfg)
	db, cleanup, err := persistence.NewDB(persistenceConfig)
	if err != nil {
		return nil, nil, err
	}
	repository := postgres.NewCredentialRepository(db)
	idGenerator := idgen.NewUUIDGenerator()
	bus := watermill.NewBus()
	registerUseCase := usecase.NewRegisterUseCase(repository, idGenerator, bus)
	jwtConfig := provideJWTConfig(cfg)
	tokenService := auth.NewJWTTokenService(jwtConfig)
	loginUseCase := usecase.NewLoginUseCase(repository, tokenService)
	refreshTokenUseCase := usecase.NewRefreshTokenUseCase(repository, tokenService)
	authHandler := handler2.NewAuthHandler(registerUseCase, loginUseCase, refreshTokenUseCase)
	app := NewApp(server, grpcServer, healthHandler, authHandler)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

func provideHTTPServer(cfg *config.AppConfig) *http.Server {
	return http.NewServer(http.ServerConfig{
		Host:         cfg.Server.HTTP.Host,
		Port:         cfg.Server.HTTP.Port,
		ReadTimeout:  cfg.Server.HTTP.ReadTimeout,
		WriteTimeout: cfg.Server.HTTP.WriteTimeout,
	}, cfg.App.Name)
}

func provideJWTConfig(cfg *config.AppConfig) auth.JWTConfig {
	return auth.JWTConfig{
		Secret:          cfg.Auth.JWT.Secret,
		AccessTokenTTL:  cfg.Auth.JWT.AccessTokenTTL,
		RefreshTokenTTL: cfg.Auth.JWT.RefreshTokenTTL,
	}
}

// providePersistenceConfig maps the load-time config aggregate onto the Identity
// BC's own persistence config, keeping the BC free of shared config types.
func providePersistenceConfig(cfg *config.AppConfig) persistence.Config {
	return persistence.Config{
		Driver:          cfg.Identity.Database.Driver,
		Host:            cfg.Identity.Database.Host,
		Port:            cfg.Identity.Database.Port,
		User:            cfg.Identity.Database.User,
		Password:        cfg.Identity.Database.Password,
		Name:            cfg.Identity.Database.Name,
		SSLMode:         cfg.Identity.Database.SSLMode,
		MaxOpenConns:    cfg.Identity.Database.MaxOpenConns,
		MaxIdleConns:    cfg.Identity.Database.MaxIdleConns,
		ConnMaxLifetime: cfg.Identity.Database.ConnMaxLifetime,
	}
}

func provideGRPCServer(cfg *config.AppConfig) *grpc.Server {
	return grpc.NewServer(grpc.ServerConfig{
		Host: cfg.Server.GRPC.Host,
		Port: cfg.Server.GRPC.Port,
	}, cfg.IsDevelopment())
}
